# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 35000:35000
