version: '3.1'

services:
  gocd-server:
    image: gocd/gocd-server:v20.8.0
    ports:
        - '8153:8153'
    container_name: gocd-server
  gocd-agent-node:
    build:
      context: .
      dockerfile: NodeAgent.Dockerfile
    depends_on:
      - gocd-server
    environment:
      GO_SERVER_URL: http://gocd-server:8153/go
      AGENT_AUTO_REGISTER_RESOURCES: 'node,npm'
    container_name: gocd-agent-node

